# Generated by Django 2.2.3 on 2019-07-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190707_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='introduce_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.FileField(upload_to=''),
        ),
    ]
