# Generated by Django 2.2.3 on 2019-07-27 07:51

import api.models.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190726_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(default='avatar/default.png', upload_to=api.models.avatar.get_image_uuid4),
        ),
    ]
