# Generated by Django 2.2.3 on 2019-08-13 03:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190727_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='user_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
