version: '3'

volumes:
  db_dev: {}

services:
  db:
    image: postgres
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=segfault
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=9306
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  backend:
    build:
      context: ./backend
      dockerfile: ../compose/backend/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=segfault
      - DJANGO_DB_USERNAME=dbuser
      - DJANGO_DB_PASSWORD=9306
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0:8000
    volumes:
      - ./backend:/backend
