version: '3'

volumes:
  postgres: {}
  redis: {}

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=segfault
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=9306
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis
    environment:
      - CLIENTHOST=server
      - CLIENTPORT=6380
      - MASTERHOST=server
      - MASTERPORT=6379
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - backend
    ports:
      - "6380:6380"
    command: --port 6380
    restart: always

  server:
    build:
      context: ./server
      dockerfile: ../compose/server/Dockerfile.dev
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=segfault.settings.dev
      - DJANGO_SECRET_KEY=dev_secret_key
      # database
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=segfault
      - DATABASE_USERNAME=dbuser
      - DATABASE_PASSWORD=9306
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6380
    volumes:
      - ./server:/server
    networks:
      - backend
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        /wait-for-it.sh postgres:5432 -t 10
        python manage.py runserver 0:8000
    restart: always
