# dev-only environment setup
version: '3.4'

volumes:
  postgres: {}
  redis: {}

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=segfault
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=9306
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:5
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - backend
    ports:
      - "6379:6379"
    restart: always

  django:
    build:
      context: ./django
      dockerfile: ../compose/django/Dockerfile.dev
    image: segfault:latest
    depends_on:
      - postgres
      - redis
    environment:
      # static files will be served by whitenoise.
      - DJANGO_SETTINGS_MODULE=core.settings.dev
      - DATABASE_URL=postgres://dbuser:9306@postgres:5432/segfault
      - REDIS_URL=redis://redis:6379
      # nuxt front-end development environment
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=3000
    volumes:
      - ./django:/django
    networks:
      - backend
    ports:
      - "8000:8000"
    command: >
      sh -c "/wait-for-it.sh postgres:5432 -t 10 &&
            python manage.py collectstatic --no-input
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000 -v3"
    restart: always
