# Generated by Django 2.2.3 on 2019-09-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190813_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='introduce_message',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
