# Generated by Django 2.2.3 on 2019-07-26 11:53

import api.models.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190726_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(default='avatar/default.png', null=True, upload_to=api.models.avatar.get_image_uuid4),
        ),
    ]
