# Generated by Django 2.2.5 on 2019-09-17 04:20

import api.models.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190905_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(default='avatar_default_image.png', upload_to=api.models.avatar.get_image_uuid4),
        ),
    ]
