# Generated by Django 2.2.5 on 2019-09-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190917_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.DecimalField(choices=[(1, 'Good'), (-1, 'Bad')], decimal_places=0, max_digits=1),
        ),
    ]
