# Generated by Django 2.2.5 on 2019-09-18 03:55

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190918_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='fragment',
            name='date_closed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'closed'}),
        ),
        migrations.AddField(
            model_name='fragment',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='open', max_length=100, no_check_for_status=True),
        ),
    ]
