# Generated by Django 2.2.5 on 2019-09-18 03:58

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190918_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='date_closed',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, when={'closed'}),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='OPEN', max_length=100, no_check_for_status=True),
        ),
    ]
