# Generated by Django 2.2.5 on 2019-09-18 03:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190918_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=16), blank=True, default=list, size=None),
        ),
    ]
