# Generated by Django 2.2.5 on 2019-09-18 04:02

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190918_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='date_closed',
            field=model_utils.fields.MonitorField(blank=True, default=None, editable=False, monitor='status', null=True, when={'CLOSED'}),
        ),
    ]
