# Generated by Django 2.2.5 on 2019-09-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190918_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_selected',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
    ]
