# Generated by Django 2.2.5 on 2019-09-22 03:15

import api.models.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190919_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(default='/static/profile.png', upload_to=api.models.avatar.get_image_uuid4),
        ),
    ]
