# Generated by Django 2.2.5 on 2019-09-22 04:06

import api.models.avatar
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190922_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_image',
            field=models.ImageField(default='profile.png', upload_to=api.models.avatar.get_image_uuid4),
        ),
    ]
