# Generated by Django 2.2.5 on 2019-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190922_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
