# Generated by Django 2.2.5 on 2019-09-24 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190923_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='allow_anonymous',
        ),
        migrations.AddField(
            model_name='room',
            name='channel_group',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
