# Generated by Django 2.2.5 on 2019-10-01 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_official', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='level',
        ),
        migrations.AddField(
            model_name='notification',
            name='_users_read',
            field=models.ManyToManyField(related_name='_notification_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='def', max_length=64),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='tags',
        ),
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Good'), (0, 'Neutral'), (-1, 'Bad')], default=0),
        ),
        migrations.AddField(
            model_name='fragment',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
