# Generated by Django 2.2.5 on 2019-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Good'), (0, 'Neutral'), (-1, 'Bad')], default=0),
        ),
    ]
