# Generated by Django 2.2.5 on 2019-10-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='content',
            field=models.CharField(max_length=2048),
        ),
    ]
