# Generated by Django 2.2.5 on 2019-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191005_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Answer for a fragment, limited length of text.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
    ]
