# Generated by Django 2.2.5 on 2019-09-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190927_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='user',
        ),
    ]
