# Generated by Django 2.2.5 on 2019-10-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191005_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Answer for a fragment, maximum length of 2048.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
