FROM python:3

ENV PYTHONUNBUFFERED 0

RUN apt-get update && apt-get -y install libpq-dev

WORKDIR /django
ADD requirements.txt /django/
RUN pip install -r requirements.txt --default-timeout=100

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /
RUN ["chmod", "u+x", "/wait-for-it.sh"]
